import type { SpotlightItem } from "./types";

export const spotlightItems: SpotlightItem[] = [
  {
    id: "spotlight-weroi",
    pillar: "Full-stack",
    title: "weROI Agency Platform",
    description:
      "Full-stack agency platform with a React SPA frontend, FastAPI Python backend, and MongoDB Atlas persistence. Built lead-capture funnels, multi-step audit forms, JWT-protected admin dashboard, Resend email integration, and REST APIs for lead management. Deployed the frontend on Vercel and the API on Railway with CORS configuration and health-check routing.",
    stack: [
      "React",
      "JavaScript",
      "TypeScript",
      "FastAPI",
      "Python",
      "MongoDB Atlas",
      "Tailwind CSS",
      "JWT",
      "Resend",
      "Vercel",
      "Railway",
      "REST APIs",
    ],
    href: "https://weroi.net",
    caseStudyHref: "/projects/weroi",
    image: "/case-studies/weroi.png",
    linkLabel: "Live site",
    accent: "#1500ff",
    tabIcon: "WR",
  },
  {
    id: "spotlight-pntcog",
    pillar: "Contract delivery",
    title: "PNTCOG Ministry Platform",
    description:
      "Multi-section React ministry website serving events, giving, prayer requests, media, and a Jubilee anniversary hub. Structured component architecture for team-friendly content updates, responsive mobile-first layouts, and performance-focused delivery on Vercel for a live congregation audience.",
    stack: [
      "React",
      "JavaScript",
      "HTML5",
      "CSS3",
      "Responsive design",
      "Vercel",
      "Component architecture",
      "React Router",
      "Accessible forms",
      "Mobile-first UI",
    ],
    href: "https://portmorentcog.org",
    caseStudyHref: "/projects/pntcog",
    image: "/case-studies/pntcog.png",
    linkLabel: "Live site",
    accent: "#d4a843",
    tabIcon: "PN",
  },
  {
    id: "spotlight-tendem-demo-bot",
    pillar: "Personal",
    title: "Telegram Demo Bot",
    description:
      "Live Telegram bot with multi-step appointment booking, support tickets, 30+ FAQ topics, and Groq/OpenAI chat. FastAPI webhook server on Railway with SQLite persistence, per-user rate limits, admin stats, and graceful FAQ fallbacks when models fail.",
    stack: [
      "Python",
      "Telegram Bot API",
      "FastAPI",
      "SQLite",
      "Groq",
      "OpenAI",
      "Webhooks",
      "LLM",
      "Railway",
    ],
    href: "https://t.me/zachtedem_bot",
    caseStudyHref: "/projects/tendem-demo-bot",
    github: "https://github.com/zacharyahutton/telegram-bot-demo",
    image: "/case-studies/tendem-demo-bot-cover.png",
    linkLabel: "Try bot",
    accent: "#0088cc",
    tabIcon: "TG",
  },
];
