import type { Project } from "../types";

export const personalProjects: Project[] = [
  {
    id: "studysync-api",
    slug: "studysync-api",
    title: "StudySync API",
    type: "personal",
    problem: "Lightweight backend to track coursework deadlines and study sessions.",
    description:
      "REST API with user auth, course modules, and deadline reminders. Built to practice FastAPI patterns, SQLAlchemy ORM, JWT-based authentication, and OpenAPI documentation.",
    stack: [
      "Python",
      "FastAPI",
      "SQL",
      "SQLite",
      "JWT",
      "Pydantic",
      "REST APIs",
      "OpenAPI",
      "pytest",
      "Uvicorn",
      "SQLAlchemy",
      "bcrypt",
      "Dependency injection",
      "Postman",
      "CRUD APIs",
    ],
    github: "https://github.com/zacharyahutton/studysync-api",
    image: "/case-studies/studysync-cover.png",
    result: "JWT-secured API with course deadline tracking endpoints",
    featured: true,
  },
  {
    id: "webhook-relay-api",
    slug: "webhook-relay-api",
    title: "Webhook Relay API",
    type: "personal",
    problem: "Developers need a sandbox to test outbound webhooks with auth and rate limits.",
    description:
      "REST API with API-key authentication, HMAC-signed webhook delivery, exponential backoff retries, and per-key rate limiting using a token bucket pattern.",
    stack: [
      "Python",
      "FastAPI",
      "JavaScript",
      "HMAC",
      "JSON",
      "REST APIs",
      "Middleware",
      "Redis",
      "Webhooks",
      "API keys",
      "Exponential backoff",
      "Token bucket rate limiting",
      "OpenAPI",
      "Async HTTP",
      "Dead-letter logging",
      "Delivery replay",
    ],
    github: "https://github.com/zacharyahutton/webhook-relay-api",
    image: "/case-studies/webhook-relay-cover.png",
    result: "Sandbox API for webhook testing with retries and rate limits",
    featured: true,
  },
  {
    id: "openapi-devkit",
    slug: "openapi-devkit",
    title: "OpenAPI DevKit",
    type: "personal",
    problem: "Quickly scaffold typed API clients from OpenAPI specs during coursework and contract work.",
    description:
      "Developer tool that ingests OpenAPI 3.x JSON, generates TypeScript fetch wrappers with Zod validation, and exports Postman collections for manual API testing.",
    stack: [
      "TypeScript",
      "Node.js",
      "JavaScript",
      "OpenAPI 3",
      "CLI",
      "Zod",
      "Code generation",
      "Fetch API",
      "Postman collections",
      "JSON Schema",
      "$ref resolution",
      "Runtime validation",
      "Dry-run mode",
    ],
    github: "https://github.com/zacharyahutton/openapi-devkit",
    image: "/case-studies/openapi-devkit-cover.png",
    result: "CLI tool for typed clients and Postman exports",
    featured: true,
  },
  {
    id: "phone-store-api",
    slug: "phone-store-api",
    title: "Phone Store REST API",
    type: "personal",
    problem: "Practice e-commerce API patterns with inventory, cart, and checkout flows.",
    description:
      "RESTful API with JWT auth, MongoDB product catalog, stock reservation middleware, and webhook handlers for order status updates.",
    stack: [
      "TypeScript",
      "Node.js",
      "Express",
      "JavaScript",
      "MongoDB",
      "REST APIs",
      "JSON",
      "JWT",
      "Refresh tokens",
      "express-rate-limit",
      "HMAC webhooks",
      "Inventory reservation",
      "Cart API",
      "Checkout flows",
      "Password hashing",
      "Pagination",
    ],
    github: "https://github.com/zacharyahutton/phone-store-api",
    image: "/case-studies/phone-store-cover.png",
    result: "E-commerce API with inventory and order webhooks",
    featured: true,
  },
  {
    id: "portfolio-site",
    slug: "portfolio-site",
    title: "Personal Portfolio",
    type: "personal",
    problem: "Present a multi-pillar engineering identity to recruiters.",
    description:
      "This site. Next.js App Router, typed content modules, obsidian design system, spotlight carousel, case study routes, and resume modal.",
    stack: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion", "HTML5", "CSS3"],
    github: "https://github.com/zacharyahutton/portfolio",
    live: "https://zachary-hutton.vercel.app",
    image: "/case-studies/portfolio-cover.png",
    result: "Open-source portfolio site on Vercel",
  },
];
