import type { Project } from "../types";

export const professionalProjects: Project[] = [
  {
    id: "pntcog",
    slug: "pntcog",
    title: "PNTCOG Ministry Platform",
    type: "professional",
    problem: "A church community needed a digital hub for events, giving, prayer, and media.",
    description:
      "Multi-section React ministry site with Jubilee anniversary hub, events calendar, giving and prayer request modules, and team-friendly content structure. Deployed on Vercel with responsive, mobile-first layouts.",
    stack: [
      "React",
      "JavaScript",
      "TypeScript",
      "HTML5",
      "CSS3",
      "Responsive design",
      "Mobile-first UI",
      "Component architecture",
      "React Router",
      "Vercel",
      "Git",
      "GitHub",
      "SEO meta tags",
      "Accessible forms",
      "Image optimization",
      "Preview deployments",
    ],
    live: "https://portmorentcog.org",
    image: "/case-studies/pntcog.png",
    result: "Live ministry platform serving events, giving, and prayer workflows",
    featured: true,
  },
  {
    id: "weroi-platform",
    slug: "weroi",
    title: "weROI Agency Platform",
    type: "professional",
    problem: "Full-stack agency platform with lead capture, admin tooling, and email integration.",
    description:
      "React SPA with FastAPI/Python backend and MongoDB Atlas. Lead-capture funnels, multi-step audit forms, JWT admin auth, Resend email integration, and deployment across Vercel and Railway.",
    stack: [
      "React",
      "JavaScript",
      "TypeScript",
      "HTML5",
      "CSS3",
      "Tailwind CSS",
      "Framer Motion",
      "GSAP",
      "React Router",
      "Radix UI",
      "react-hook-form",
      "Zod",
      "FastAPI",
      "Python",
      "Pydantic",
      "MongoDB Atlas",
      "REST APIs",
      "JWT",
      "Resend",
      "APScheduler",
      "Vercel",
      "Railway",
      "CORS",
      "Admin dashboard",
      "Lead capture",
      "Multi-step forms",
      "Analytics events",
    ],
    live: "https://weroi.net",
    github: "https://github.com/zacharyahutton/weROI",
    image: "/case-studies/weroi.png",
    result: "Production agency stack with admin dashboard and lead funnels",
    featured: true,
  },
];
