import { withReadingMeta } from "../types";

export const pntcogMinistrySitePost = withReadingMeta({
  id: "pntcog-ministry-site",
  title: "Building a Mobile First Church Website with Next.js and Real Content Architecture",
  blurb:
    "How I designed a mobile first church website for PNTCOG with Next.js routes, ministry pages, and content that still works on a phone for Portmore visitors.",
  tag: "Case study",
  date: "January 2026",
  publishedAt: "2026-01-24",
  href: "/blog/pntcog-ministry-site",
  image: "/blog/pntcog-ministry-site.png",
  primaryKeyword: "mobile first church website",
  intro: [
    "A church website gets used in very specific moments. Someone is standing outside looking for service times on their phone. A member opens the giving page on mobile data to make a donation before service starts. A parent shares an event link in a WhatsApp group. Each of those moments involves a small screen, a slow connection, and a visitor who needs one clear answer.",
    "When I built the mobile first church website for Port Morant New Testament Church of God (PNTCOG), I had to confront the gap between what ministry websites usually look like and what their visitors actually need. This post covers the content architecture, the mobile-first engineering decisions, and the lessons I learned about building a church website with Next.js that genuinely serves a community in Portmore and beyond.",
  ],
  sections: [
    {
      heading: "Why Ministry Website Design Usually Fails",
      paragraphs: [
        "Most church websites treat content as a brochure. There is a homepage with a welcome message, a few photos, maybe a service schedule somewhere in the footer, and a contact page. Everything is one or two levels deep, and the information visitors actually need is buried.",
        "The problem is that a church website serves multiple audiences with different urgency levels. First-time visitors need location, service times, and what to expect. Regular members need event schedules, ministry updates, and giving links. Leaders need administrative pages and CMS access. A single-page brochure cannot serve all three groups without forcing someone to scroll through content that is not for them.",
        "I approached the PNTCOG site with the principle that every page should answer one clear question. If someone arrives looking for the youth ministry schedule, they should land on a dedicated youth ministry page, not a homepage section titled 'Our Ministries' with five thumbnails and a 'learn more' button that leads to a PDF.",
      ],
    },
    {
      heading: "Content Architecture: One Route, One Purpose",
      paragraphs: [
        "The information architecture of the PNTCOG site is route-based. Each ministry has its own page. Events have a dedicated hub. Giving has its own page with clear instructions. Leadership has a page. The belief statement has a page. These are not decorative, they are functional routes that can be shared, bookmarked, and indexed by search engines.",
        "This approach has concrete benefits. When someone searches 'Port Morant Church of God youth ministry', the dedicated page can rank for that query because it has a unique title, description, and content. A section on the homepage cannot do that. When a church leader wants to share the giving page in a group chat, they share a clean URL like portmorentcog.org/giving, not a homepage link with instructions to 'scroll down to the giving section'.",
        "I built the routes in Next.js using the App Router. Each route has its own metadata (title, description, Open Graph image) generated by the generateMetadata function. Static params generate all known routes at build time so the site deploys as static HTML with no runtime server required. This means fast page loads even on the slower mobile connections common in Jamaica.",
      ],
      bullets: [
        "Every ministry route has a unique page title and meta description for search visibility.",
        "Static generation means the site loads fast without a running server.",
        "Shareable URLs work in WhatsApp, Facebook, and other platforms where church members actually share links.",
        "The route structure matches how people navigate: /ministries/youth, /events, /giving, /about/leadership.",
      ],
    },
    {
      heading: "Building Mobile First for Real Conditions",
      paragraphs: [
        "Mobile first does not mean shrinking the desktop layout until it fits a phone. It means designing for the phone first and expanding for larger screens. This distinction matters when your primary audience uses Android phones on variable mobile data, which is the reality for most of the PNTCOG congregation.",
        "I started every layout decision at 320px width. Navigation had to work with a thumb on a 5-inch screen. Text had to be readable without zooming. Tap targets had to be at least 44px. Images had to load progressively and not block the visible content. Forms (like the contact form and giving page CTAs) had to be usable with a phone keyboard.",
        "The header is a core example. On mobile, it collapses to a compact bar with the church monogram and a hamburger menu. The menu opens as a full-screen sheet with large, well-spaced links. Ministry sub-pages are grouped under an expandable section so the menu stays manageable. On desktop, the full navigation bar appears with dropdown menus. But the mobile experience is the primary experience, designed first and tested most.",
      ],
      subheadings: [
        {
          heading: "Image handling for slow connections",
          paragraphs: [
            "Church websites love hero images, but large unoptimized photos are the fastest way to lose a mobile visitor. I used Next.js Image optimization to serve responsive sizes and modern formats (WebP). Hero images load with priority, while below-the-fold images lazy-load. For the gallery sections on the giving and reservation pages, I used a masonry layout that loads images progressively as the user scrolls.",
            "I also audited every image in the site's asset library. Seven ministry detail images were returning 404 on the live site. I replaced them with placeholder images sourced from actual church photography until dedicated ministry art is provided. A broken image is worse than no image at all.",
          ],
        },
      ],
    },
    {
      heading: "The CMS Layer and Content Workflow",
      paragraphs: [
        "A church website needs to be updatable by non-developers. Service times change. Events happen weekly. Ministry leaders want to update their page content. This means the site needs a content management layer, even if it starts simple.",
        "I built a CMS integration layer using Supabase for structured content and a set of data-cms-field attributes in the markup so the admin interface knows which content blocks are editable. The CMS is a parallel track: the public site works perfectly with static content baked at build time, and the CMS layer adds dynamic updates when connected.",
        "The admin wiring is documented in the project's CMS integration guide. Environment variables connect the frontend to Supabase, and a revalidation webhook lets the CMS trigger static regeneration when content changes. This means the site stays fast (static HTML) while supporting content updates without a redeploy.",
      ],
      bullets: [
        "Static content works out of the box. CMS is an enhancement, not a dependency.",
        "data-cms-field attributes make content blocks discoverable for the admin editor.",
        "Revalidation webhooks update static pages without a full rebuild.",
        "Content decisions (what goes on each page, how it is structured) are documented so future updates stay consistent.",
      ],
    },
    {
      heading: "Design Tokens and the Church Brand",
      paragraphs: [
        "A church website should look like that specific church, not like a template. PNTCOG has a visual identity: specific colors (gold/champagne accents on a clean background), a monogram, a tone that is welcoming but not casual. I translated that identity into a token system that controls colors, typography, spacing, and component styles across the entire site.",
        "The token system uses an 8px spacing rhythm, 20px card border radius, weight-500 headings, and a palette derived from the church brand. Dark mode and light mode share the same token structure with different values. Components like buttons, cards, and section containers pull from tokens instead of hardcoding styles, so the brand is consistent whether you are on the homepage, a ministry page, or the giving page.",
        "I also added scroll-reveal animations using GSAP ScrollTrigger for editorial prose sections on key pages: home, belief, history, giving, and events. The animations are subtle and respect reduced-motion preferences. They add polish without overwhelming the content.",
      ],
    },
    {
      heading: "What I Learned About Church Website Next.js Development",
      paragraphs: [
        "The biggest lesson was that content architecture is accessibility. When every page answers a real question and works comfortably on a phone, the site serves the community instead of simply representing it. A visitor in Portmore on a 4G connection should have the same quality experience as someone on Wi-Fi.",
        "The second lesson was about stakeholder communication. Preview deployments were essential. Instead of describing what a page would look like, I could share a URL and ask for feedback on the actual content, layout, and navigation. That made conversations specific and reduced the number of rounds needed to finalize each page.",
        "The third lesson was about durability. A church website is not a campaign site. It needs to be maintainable for years, by people who are not the original developer. Clean routes, documented content decisions, a CMS layer, and a simple deployment pipeline all contribute to a site that survives the handoff.",
      ],
    },
  ],
  faqs: [
    {
      question: "What is the best framework for building a church website?",
      answer:
        "Next.js is an excellent choice because it supports static generation (fast page loads, no server required), has built-in image optimization, and generates clean metadata for search engines. For a church website, most content is static and changes infrequently, so static generation gives you speed and simplicity. The App Router makes it easy to create dedicated routes for ministries, events, and giving pages.",
    },
    {
      question: "How do you make a church website mobile first?",
      answer:
        "Start every design decision at the smallest screen size (320px). Navigation should work with a thumb. Text should be readable without zooming. Tap targets should be at least 44px. Images should be optimized and lazy-loaded below the fold. Test on real phones over real mobile connections, not just in a browser resized to a small window. Mobile first means the phone layout is designed first and the desktop layout expands from there.",
    },
    {
      question: "Does a small church need a CMS for their website?",
      answer:
        "Not immediately, but plan for one. A statically generated site works well initially, and you can add a CMS layer later without rebuilding. The important thing is to structure your content so it is editable: clear routes, separated content blocks, and documented content decisions. When the church is ready for a CMS, the transition is straightforward because the architecture already supports it.",
    },
    {
      question: "How do you handle ministry subpages on a church website?",
      answer:
        "Give each ministry its own route with a unique title, description, and content. This is better than a single page listing all ministries because individual routes are searchable, shareable, and can be linked from WhatsApp or social media. In Next.js, you can use dynamic routes with generateStaticParams to build all ministry pages at deploy time from a content collection.",
    },
    {
      question: "How important is page speed for a church website?",
      answer:
        "Very important, especially in communities where visitors access the site on mobile data. A slow-loading page will lose someone who just needs service times or the giving link. Static generation, image optimization, lazy loading, and minimal JavaScript all contribute to fast page loads. Test your site on a throttled 3G connection to understand the real experience.",
    },
  ],
  takeaway:
    "Content architecture is the foundation of a useful church website. When every page answers a real question and works comfortably on a phone, the site serves the community instead of simply representing it. Build mobile first, give each ministry its own route, optimize for slow connections, and plan for maintainability.",
  relatedLink: {
    label: "Explore the PNTCOG project",
    href: "/projects/pntcog",
  },
});
